### ISSUE TITLE
Метод НайтиФайлы() вызывает Внешнее исключение

### ISSUE THREAD

**Issue by k2589** [dmpas/oscript-ftp#6]
Данный код: 
`МассивНайденныхКаталогов = Соединение.НайтиФайлы("/");`
выводит в консоле следующее сообщение:
```
{Модуль C:\Files\FTP.os / Ошибка в строке: 22 / Внешнее исключение (System.MissingMethodException): Метод не найден: "ScriptEngine.Machine.IRuntimeContextInstance ScriptEngine.HostedScript.Library.ArrayImpl.Constructor()".}    
    МассивНайденныхКаталогов = Соединение.НайтиФайлы("/");

```

**Comment by milanse** [comment]
А будет это все переливаться в мастер ? Публиковаться для обновления библиотек ?

**Comment by dmpas** [comment]
@milanse благодарю за пендыль. Занялся вопросом.

**Comment by milanse** [comment]
Спасибо, пока поставил ручками, но обновление opm автоматом затирает более ранней версией.
